package com.luowei.virusmap.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class Virusdata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.confirm
     *
     * @mbg.generated
     */
    private Integer confirm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.suspect
     *
     * @mbg.generated
     */
    private Integer suspect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.heal
     *
     * @mbg.generated
     */
    private Integer heal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column virusdata.dead
     *
     * @mbg.generated
     */
    private Integer dead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.id
     *
     * @return the value of virusdata.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.id
     *
     * @param id the value for virusdata.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.name
     *
     * @return the value of virusdata.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.name
     *
     * @param name the value for virusdata.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.province
     *
     * @return the value of virusdata.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.province
     *
     * @param province the value for virusdata.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.confirm
     *
     * @return the value of virusdata.confirm
     *
     * @mbg.generated
     */
    public Integer getConfirm() {
        return confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.confirm
     *
     * @param confirm the value for virusdata.confirm
     *
     * @mbg.generated
     */
    public void setConfirm(Integer confirm) {
        this.confirm = confirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.suspect
     *
     * @return the value of virusdata.suspect
     *
     * @mbg.generated
     */
    public Integer getSuspect() {
        return suspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.suspect
     *
     * @param suspect the value for virusdata.suspect
     *
     * @mbg.generated
     */
    public void setSuspect(Integer suspect) {
        this.suspect = suspect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.heal
     *
     * @return the value of virusdata.heal
     *
     * @mbg.generated
     */
    public Integer getHeal() {
        return heal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.heal
     *
     * @param heal the value for virusdata.heal
     *
     * @mbg.generated
     */
    public void setHeal(Integer heal) {
        this.heal = heal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column virusdata.dead
     *
     * @return the value of virusdata.dead
     *
     * @mbg.generated
     */
    public Integer getDead() {
        return dead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column virusdata.dead
     *
     * @param dead the value for virusdata.dead
     *
     * @mbg.generated
     */
    public void setDead(Integer dead) {
        this.dead = dead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", province=").append(province);
        sb.append(", confirm=").append(confirm);
        sb.append(", suspect=").append(suspect);
        sb.append(", heal=").append(heal);
        sb.append(", dead=").append(dead);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Virusdata other = (Virusdata) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getConfirm() == null ? other.getConfirm() == null : this.getConfirm().equals(other.getConfirm()))
            && (this.getSuspect() == null ? other.getSuspect() == null : this.getSuspect().equals(other.getSuspect()))
            && (this.getHeal() == null ? other.getHeal() == null : this.getHeal().equals(other.getHeal()))
            && (this.getDead() == null ? other.getDead() == null : this.getDead().equals(other.getDead()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getConfirm() == null) ? 0 : getConfirm().hashCode());
        result = prime * result + ((getSuspect() == null) ? 0 : getSuspect().hashCode());
        result = prime * result + ((getHeal() == null) ? 0 : getHeal().hashCode());
        result = prime * result + ((getDead() == null) ? 0 : getDead().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        province("province", "province", "VARCHAR", false),
        confirm("confirm", "confirm", "INTEGER", false),
        suspect("suspect", "suspect", "INTEGER", false),
        heal("heal", "heal", "INTEGER", false),
        dead("dead", "dead", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table virusdata
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}