package com.luowei.virusmap.dao;

import com.luowei.virusmap.domain.Incity;
import com.luowei.virusmap.domain.IncityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IncityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    long countByExample(IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int deleteByExample(IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int insert(Incity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int insertSelective(Incity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    Incity selectOneByExample(IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    Incity selectOneByExampleSelective(@Param("example") IncityExample example, @Param("selective") Incity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    List<Incity> selectByExampleSelective(@Param("example") IncityExample example, @Param("selective") Incity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    List<Incity> selectByExample(IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    Incity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Incity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    Incity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Incity record, @Param("example") IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Incity record, @Param("example") IncityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Incity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table incity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Incity record);
}