package com.luowei.virusmap.dao;

import com.luowei.virusmap.domain.Outcity;
import com.luowei.virusmap.domain.OutcityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutcityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    long countByExample(OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int deleteByExample(OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int insert(Outcity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int insertSelective(Outcity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    Outcity selectOneByExample(OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    Outcity selectOneByExampleSelective(@Param("example") OutcityExample example, @Param("selective") Outcity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    List<Outcity> selectByExampleSelective(@Param("example") OutcityExample example, @Param("selective") Outcity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    List<Outcity> selectByExample(OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    Outcity selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Outcity.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    Outcity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Outcity record, @Param("example") OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Outcity record, @Param("example") OutcityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Outcity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outcity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Outcity record);
}