package com.luowei.virusmap.dao;

import com.luowei.virusmap.domain.Virusdata;
import com.luowei.virusmap.domain.VirusdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VirusdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    long countByExample(VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int deleteByExample(VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int insert(Virusdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int insertSelective(Virusdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    Virusdata selectOneByExample(VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    Virusdata selectOneByExampleSelective(@Param("example") VirusdataExample example, @Param("selective") Virusdata.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    List<Virusdata> selectByExampleSelective(@Param("example") VirusdataExample example, @Param("selective") Virusdata.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    List<Virusdata> selectByExample(VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    Virusdata selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Virusdata.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    Virusdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Virusdata record, @Param("example") VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Virusdata record, @Param("example") VirusdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Virusdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table virusdata
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Virusdata record);
}